#pragma once
#include "constants.h"

void addBook(char bookISBNs[MAX_BOOKS][20],
             char bookTitles[MAX_BOOKS][100],
             char bookAuthors[MAX_BOOKS][50],
             char bookEditions[MAX_BOOKS][50],
             char bookPublishers[MAX_BOOKS][50],
             int bookYearsOfPublication[MAX_BOOKS],
             char bookGenres[MAX_BOOKS][50],
             float bookPrices[MAX_BOOKS],
             int bookQuantities[MAX_BOOKS],
             int &bookCount);
void editBook(char bookISBNs[MAX_BOOKS][20],
              char bookTitles[MAX_BOOKS][100],
              char bookAuthors[MAX_BOOKS][50],
              char bookEditions[MAX_BOOKS][50],
              char bookPublishers[MAX_BOOKS][50],
              int bookYearsOfPublication[MAX_BOOKS],
              char bookGenres[MAX_BOOKS][50],
              float bookPrices[MAX_BOOKS],
              int bookQuantities[MAX_BOOKS],
              int &bookCount);
void deleteBook(char bookISBNs[MAX_BOOKS][20],
                char bookTitles[MAX_BOOKS][100],
                char bookAuthors[MAX_BOOKS][50],
                char bookEditions[MAX_BOOKS][50],
                char bookPublishers[MAX_BOOKS][50],
                int bookYearsOfPublication[MAX_BOOKS],
                char bookGenres[MAX_BOOKS][50],
                float bookPrices[MAX_BOOKS],
                int bookQuantities[MAX_BOOKS],
                int &bookCount);
void searchBookByISBN(char bookISBNs[MAX_BOOKS][20],
                      char bookTitles[MAX_BOOKS][100],
                      char bookAuthors[MAX_BOOKS][50],
                      char bookEditions[MAX_BOOKS][50],
                      char bookPublishers[MAX_BOOKS][50],
                      int bookYearsOfPublication[MAX_BOOKS],
                      char bookGenres[MAX_BOOKS][50],
                      float bookPrices[MAX_BOOKS],
                      int bookQuantities[MAX_BOOKS],
                      int bookCount);
void searchBookByTitle(char bookISBNs[MAX_BOOKS][20],
                       char bookTitles[MAX_BOOKS][100],
                       char bookAuthors[MAX_BOOKS][50],
                       char bookEditions[MAX_BOOKS][50],
                       char bookPublishers[MAX_BOOKS][50],
                       int bookYearsOfPublication[MAX_BOOKS],
                       char bookGenres[MAX_BOOKS][50],
                       float bookPrices[MAX_BOOKS],
                       int bookQuantities[MAX_BOOKS],
                       int bookCount);